# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fillConstraintMatrixGaps <- function(M, MinGap) {
    .Call(`_DispatchOptimizationEngine_fillConstraintMatrixGaps`, M, MinGap)
}

optimizeBatteryStorageDP <- function(BatteryData, LoadVector, ChargeStates, TransitionList, initial_state, final_state) {
    .Call(`_DispatchOptimizationEngine_optimizeBatteryStorageDP`, BatteryData, LoadVector, ChargeStates, TransitionList, initial_state, final_state)
}

optimizeGeneration <- function(CommitMatrix, AlwaysOn, PlantParameters, UnitList, StateGenerationMatrix, StateHeatRateMatrix, PowerPriceVector, LoadVector, HourIndexList) {
    .Call(`_DispatchOptimizationEngine_optimizeGeneration`, CommitMatrix, AlwaysOn, PlantParameters, UnitList, StateGenerationMatrix, StateHeatRateMatrix, PowerPriceVector, LoadVector, HourIndexList)
}

optimizeUnitCommitmentDP <- function(OptParameters, PlantParameters, UnitList, PowerPriceVector, LoadVector, MustRunMatrix, OutageMatrix, StackOnMatrix, StackOffMatrix, HourIndexList, InitialState) {
    .Call(`_DispatchOptimizationEngine_optimizeUnitCommitmentDP`, OptParameters, PlantParameters, UnitList, PowerPriceVector, LoadVector, MustRunMatrix, OutageMatrix, StackOnMatrix, StackOffMatrix, HourIndexList, InitialState)
}

rcpparma_hello_world <- function() {
    .Call(`_DispatchOptimizationEngine_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_DispatchOptimizationEngine_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_DispatchOptimizationEngine_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_DispatchOptimizationEngine_rcpparma_bothproducts`, x)
}

stackCut <- function(PlantParameters, LoadMatrix, OutageMatrix, MustRunMatrix, PowerPrice, HourIndexList, IncludeUnit) {
    .Call(`_DispatchOptimizationEngine_stackCut`, PlantParameters, LoadMatrix, OutageMatrix, MustRunMatrix, PowerPrice, HourIndexList, IncludeUnit)
}

sumCpp <- function(x) {
    .Call(`_DispatchOptimizationEngine_sumCpp`, x)
}

